### ISSUE TITLE
KIP-823/KIP-809 is still under draft, but get marked as black

### ISSUE THREAD

**Issue by showuon** [tomncooper/ossip#1]
[KIP-823](https://wiki.apache.org/confluence/display/KAFKA/KIP-823%3A++Update+Admin%3A%3AdescribeConfigs+to+allow+fetching+specific+configurations) and [KIP-809](https://wiki.apache.org/confluence/pages/viewpage.action?pageId=199527406) are under draft, have not started any discussion in dev group. However, they are marked as "black". I think it'd be better to filter them out since they are still drafting the KIPs. 

Thank you.

**Comment by tomncooper** [comment]
Thanks for pointing that out @showuon. 

The list of KIPs is derived by looking at all KIP wiki pages that have state = Under Discussion (or similar). In the case of 809 it has "WIP" as the state which I take as meaning under discussion and 823 has "Under Discussion" so that is why it is included in the list. The status of both is black as neither has been mentioned in an email subject line in the last 2 years of emails.

In the case of 823 this is probably because the proposal is not finished yet so is being worked on. In the case of 809 it is several months old and the wiki is not filled in so that one is probably "stale", so black is appropriate.

It would be good if we could agree a "Draft" state for new KIPs that are yet to be released on the mailing list. I could then label these with Blue. I could also label any KIP created in the last month with no emails in Blue anyway as if it has no announcement email it probably in draft. WDYT?

**Comment by tomncooper** [comment]
I have updated the table to show blue if a KIP was created in the last month but has no mentions.

**Comment by showuon** [comment]
> I could also label any KIP created in the last month with no emails in Blue anyway as if it has no announcement email it probably in draft.

Sounds good. Thanks for the fix!
